# Generated by Django 2.2.3 on 2019-07-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='headimg',
            field=models.FileField(default=' ', upload_to='img/'),
        ),
    ]
