# Generated by Django 2.2.3 on 2019-07-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_headimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('headimg', models.FileField(default=' ', upload_to='img/')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='headimg',
        ),
    ]
