# Generated by Django 2.2.3 on 2019-07-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190712_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='headimg',
            field=models.FileField(default=' ', upload_to='./img/'),
        ),
    ]
