# Generated by Django 2.2.3 on 2019-07-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190712_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='style',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='img',
            name='headimg',
            field=models.FileField(default=' ', upload_to='xiaoxin/'),
        ),
        migrations.CreateModel(
            name='user_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(default='', upload_to='user_imgs')),
                ('img_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
        ),
    ]
